package io.github.mnvkalyansambhana.offgridvault.autofill

/**
 * Browsers whose reported `webDomain` is trusted (S14, S31): package + SHA-256 of the signing
 * cert, from the bundled `browsers.txt` (generated by tools/update_browsers.py).
 */
class BrowserAllowlist(lines: Sequence<String>) {

    private val certsByPackage: Map<String, Set<String>> = lines
        .map { it.trim() }
        .filter { it.isNotEmpty() && !it.startsWith("#") }
        .map { it.split(' ') }
        .filter { it.size == 2 && it[1].length == 64 }
        .groupBy({ it[0] }, { it[1].lowercase() })
        .mapValues { it.value.toSet() }

    /** [certs] = hex SHA-256 of the requester's current signing certs. */
    fun isBrowser(packageName: String, certs: Set<String>): Boolean {
        val allowed = certsByPackage[packageName] ?: return false
        return certs.any { it in allowed }
    }

    companion object {
        private const val RESOURCE = "/io/github/mnvkalyansambhana/offgridvault/autofill/browsers.txt"

        val bundled: BrowserAllowlist by lazy {
            val stream = checkNotNull(BrowserAllowlist::class.java.getResourceAsStream(RESOURCE)) { "browser list missing" }
            stream.bufferedReader(Charsets.UTF_8).useLines { BrowserAllowlist(it.toList().asSequence()) }
        }
    }
}
