package io.github.mnvkalyansambhana.offgridvault.ui.vault

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import io.github.mnvkalyansambhana.offgridvault.AppContainer
import io.github.mnvkalyansambhana.offgridvault.core.crypto.wipe
import io.github.mnvkalyansambhana.offgridvault.core.vault.EntryDraft
import io.github.mnvkalyansambhana.offgridvault.core.vault.PasswordGenerator
import io.github.mnvkalyansambhana.offgridvault.core.vault.VaultSession
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

/**
 * Add / edit a login (P10, C15). Form text is Compose state (Strings — best effort, S25); it's
 * cleared when the screen goes away. A changed password moves the old one into history.
 */
class EntryEditViewModel(private val app: AppContainer, val entryId: String?) : ViewModel() {

    var title by mutableStateOf("")
    var username by mutableStateOf("")
    var password by mutableStateOf("")
    var notes by mutableStateOf("")
    val urls = mutableStateListOf("")
    var showPassword by mutableStateOf(false)
    var saving by mutableStateOf(false)
        private set
    var error by mutableStateOf<String?>(null)
        private set

    // Generator sheet (P10)
    var generatorOpen by mutableStateOf(false)
        private set
    var generatorOptions by mutableStateOf(PasswordGenerator.Options())
        private set
    var generated by mutableStateOf("")
        private set

    val isNew: Boolean get() = entryId == null

    init {
        val unlocked = app.session.state.value as? VaultSession.State.Unlocked
        val entry = entryId?.let { unlocked?.content?.entry(it) }
        if (unlocked != null && entry != null) {
            title = entry.title
            username = entry.username
            password = reveal(unlocked, entry.password)
            notes = reveal(unlocked, entry.notes)
            urls.clear()
            urls.addAll(entry.urls.ifEmpty { listOf("") })
        }
    }

    fun addUrl() {
        urls.add("")
    }

    fun openGenerator() {
        generatorOpen = true
        regenerate()
    }

    fun closeGenerator() {
        generatorOpen = false
        generated = ""
    }

    fun updateOptions(options: PasswordGenerator.Options) {
        generatorOptions = options
        regenerate()
    }

    fun regenerate() {
        val chars = PasswordGenerator.generate(generatorOptions)
        generated = String(chars)
        chars.wipe()
    }

    /** P10: the generated password goes straight into the form, never the clipboard. */
    fun useGenerated() {
        password = generated
        showPassword = true
        closeGenerator()
    }

    fun save(onSaved: () -> Unit) {
        val unlocked = app.session.state.value as? VaultSession.State.Unlocked ?: return
        if (title.isBlank()) {
            error = "Give this login a title"
            return
        }
        saving = true
        val passwordBytes = password.toByteArray(Charsets.UTF_8)
        val notesBytes = notes.toByteArray(Charsets.UTF_8)
        val draft = EntryDraft(entryId, title, username, urls.toList(), passwordBytes, notesBytes)
        viewModelScope.launch {
            withContext(Dispatchers.IO) {
                try {
                    val updated = unlocked.content.upsert(draft, System.currentTimeMillis())
                    app.session.save(app.repository, updated)
                } finally {
                    passwordBytes.wipe()
                    notesBytes.wipe()
                }
            }
            saving = false
            clearForm()
            onSaved()
        }
    }

    private fun reveal(unlocked: VaultSession.State.Unlocked, secret: io.github.mnvkalyansambhana.offgridvault.core.vault.SealedSecret): String {
        val bytes = unlocked.content.reveal(secret)
        return try {
            String(bytes, Charsets.UTF_8)
        } finally {
            bytes.wipe()
        }
    }

    private fun clearForm() {
        password = ""
        notes = ""
        generated = ""
    }

    override fun onCleared() = clearForm()
}
