#!/usr/bin/env python3
"""Regenerates the S31 browser allowlist from Google's Credential Manager privileged-apps list.

Run on a dev machine (the app itself never goes online), review the diff, commit:
    python3 tools/update_browsers.py
Keeps browsers only and release signatures only. Never add a package by hand without its cert.
"""
import json
import urllib.request

SOURCE = "https://www.gstatic.com/gpm-passkeys-privileged-apps/apps.json"
OUT = "autofill/src/main/resources/io/github/mnvkalyansambhana/offgridvault/autofill/browsers.txt"

# Not browsers (system services, VPN/workspace clients, credential/FIDO clients).
NOT_BROWSERS = {
    "com.google.android.gms",
    "com.citrix.Receiver",
    "com.fido.fido2client",
    "com.oplus.credential",
}
# Signed with publicly available keys (AOSP test key / Chromium's checked-in debug keystore) or
# developer reference builds: anyone could produce an app with the listed cert.
UNSAFE = {"com.android.browser", "org.chromium.chrome", "org.mozilla.reference.browser"}


def main():
    with urllib.request.urlopen(SOURCE, timeout=60) as response:
        apps = json.load(response)["apps"]
    lines = []
    for app in apps:
        if app.get("type") != "android":
            continue
        info = app["info"]
        package = info["package_name"]
        if package in NOT_BROWSERS or package in UNSAFE or "debug" in package:
            continue
        for signature in info["signatures"]:
            if signature.get("build") != "release":
                continue
            cert = signature["cert_fingerprint_sha256"].replace(":", "").lower()
            assert len(cert) == 64, (package, cert)
            lines.append(f"{package} {cert}")
    with open(OUT, "w") as out:
        out.write(f"# S31 browser allowlist: package SHA-256(signing cert). Generated by tools/update_browsers.py from\n# {SOURCE}\n")
        out.write("\n".join(sorted(set(lines))) + "\n")
    print(f"{len(lines)} signatures written to {OUT}")


if __name__ == "__main__":
    main()
